var search={
  "3D Model of CIIC 153": "http://Research-Squirrel-Engineers.io/3dannotation_example/CIIC_153_3dmodel",
  "3D Model of Ogham Stone": "http://Research-Squirrel-Engineers.io/3dannotation_example/ogham_stone_3dmodel",
  "3D Model of Tullaherin_II": "http://Research-Squirrel-Engineers.io/3dannotation_example/Tullaherin_II_3dmodel",
  "3DModel Instances Collection": "http://Research-Squirrel-Engineers.io/3dannotation_example/3DModel_collection",
  "Annotation Instances Collection": "http://Research-Squirrel-Engineers.io/3dannotation_example/Annotation_collection",
  "Annotation body  of a cross on I-KER-062.obj": "http://Research-Squirrel-Engineers.io/3dannotation_example/ogham_stone_3dmodel_crossanno_body1",
  "Annotation body of \u1689 on CIIC 153": "http://Research-Squirrel-Engineers.io/3dannotation_example/CIIC_153_3dmodel_c1_anno_body",
  "Annotation of a cross on I-KER-062.obj": "http://Research-Squirrel-Engineers.io/3dannotation_example/Tullaherin_II_3dmodel_dt_anno",
  "Annotation of \u1689 on CIIC 153": "http://Research-Squirrel-Engineers.io/3dannotation_example/CIIC_153_3dmodel_c1_anno",
  "Annotation target of a cross on I-KER-062.obj": "http://Research-Squirrel-Engineers.io/3dannotation_example/ogham_stone_3dmodel_crossanno_target",
  "Annotation target of \u1689 on CIIC 153": "http://Research-Squirrel-Engineers.io/3dannotation_example/CIIC_153_3dmodel_c1_anno_target",
  "Annotation target selector of Ogham D[...]T (\u1687[...]\u1688) on Tullaherin_II.obj": "http://Research-Squirrel-Engineers.io/3dannotation_example/Tullaherin_II_3dmodel_dt_anno_target_selector",
  "Annotation target selector of a cross on I-KER-062.obj": "http://Research-Squirrel-Engineers.io/3dannotation_example/ogham_stone_3dmodel_crossanno_target_selector",
  "Annotation target selector of \u1689 on CIIC 153": "http://Research-Squirrel-Engineers.io/3dannotation_example/CIIC_153_3dmodel_c1_anno_target_selector",
  "CIIC 153": "http://Research-Squirrel-Engineers.io/3dannotation_example/CIIC_153",
  "Cartesian coordinate system with 3 axis in millimetre units": "http://Research-Squirrel-Engineers.io/3dannotation_example/cartesian_ax3_mm",
  "Cartesian coordinate system with 3 axis in millimetre units: Axis 1": "http://Research-Squirrel-Engineers.io/3dannotation_example/cartesian_ax3_mm_axis1",
  "Cartesian coordinate system with 3 axis in millimetre units: Axis 2": "http://Research-Squirrel-Engineers.io/3dannotation_example/cartesian_ax3_mm_axis2",
  "Cartesian coordinate system with 3 axis in millimetre units: Axis 3": "http://Research-Squirrel-Engineers.io/3dannotation_example/ont#cartesian_ax3_mm_axis3",
  "CartesianCS Instances Collection": "http://Research-Squirrel-Engineers.io/3dannotation_example/CartesianCS_collection",
  "CoordinateSystemAxis Instances Collection": "http://Research-Squirrel-Engineers.io/3dannotation_example/CoordinateSystemAxis_collection",
  "Ogham Stone": "http://Research-Squirrel-Engineers.io/3dannotation_example/ogham_stone",
  "OghamStone Instances Collection": "http://Research-Squirrel-Engineers.io/3dannotation_example/OghamStone_collection",
  "Polygon Instances Collection": "http://Research-Squirrel-Engineers.io/3dannotation_example/Polygon_collection",
  "Tullaherin_II": "http://Research-Squirrel-Engineers.io/3dannotation_example/Tullaherin_II",
  "WKTSelector Instances Collection": "http://Research-Squirrel-Engineers.io/3dannotation_example/WKTSelector_collection"
}